# Generated by Django 4.2.9 on 2026-03-26 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('REGISTER', 'Inscription'), ('CONSULTATION_CREATED', 'Consultation créée'), ('CONSULTATION_ACCEPTED', 'Consultation acceptée'), ('CONSULTATION_COMPLETED', 'Consultation terminée'), ('CONSULTATION_CANCELLED', 'Consultation annulée'), ('PRESCRIPTION_CREATED', 'Ordonnance créée'), ('PRESCRIPTION_VERIFIED', 'Ordonnance vérifiée'), ('PRESCRIPTION_DISPENSED', 'Ordonnance délivrée'), ('PAYMENT_CONFIRMED', 'Paiement confirmé'), ('DOCTOR_STATUS_CHANGED', 'Statut médecin modifié'), ('PROFILE_UPDATED', 'Profil mis à jour'), ('PUBLIC_KEY_UPLOADED', 'Clé publique uploadée'), ('OTHER', 'Autre action')], db_index=True, default='OTHER', help_text="Type d'action effectuée", max_length=50)),
                ('details', models.TextField(blank=True, help_text="Détails de l'action (ID de ressource, etc.)")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP du client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Horodatage de l'action")),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur ayant effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
    ]
