# Generated by Django 4.2.9 on 2026-03-16 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_recues', to=settings.AUTH_USER_MODEL)),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
