# Generated by Django 4.2.9 on 2026-03-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('consultations', '0002_remove_consultation_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
            preserve_default=False,
        ),
    ]
