# Generated by Django 4.2.9 on 2026-03-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='Ex: Pénicilline, Aspirine...')),
                ('antecedents', models.TextField(blank=True, help_text='Maladies chroniques, opérations...')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.PositiveIntegerField(blank=True, null=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
        ),
    ]
