# Generated by Django 4.2.9 on 2026-03-21 03:56

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Ex: Pénicilline, Aspirine...'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='antecedents',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Maladies chroniques, opérations...'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='groupe_sanguin',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=5),
        ),
    ]
