# Generated by Django 4.2.9 on 2026-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nom_customuser_prenom_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Cocher pour autoriser l'accès complet à l'application."),
        ),
    ]
