# Generated by Django 4.2.9 on 2026-03-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='photo_pharmacie',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies/photos/'),
        ),
    ]
