# Generated by Django 4.2.9 on 2026-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='cin_numero',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='document_cin',
            field=models.FileField(blank=True, null=True, upload_to='doctors/documents/cin/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='document_cnom',
            field=models.FileField(blank=True, null=True, upload_to='doctors/documents/cnom/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gouvernorat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('OFFLINE', 'Hors ligne'), ('ONLINE', 'En ligne'), ('BUSY', 'Occupé')], default='OFFLINE', max_length=20),
        ),
    ]
