# Generated by Django 4.2.9 on 2026-03-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorprofile_cin_numero_doctorprofile_document_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistprofile',
            name='cin_numero',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='document_autorisation',
            field=models.FileField(blank=True, null=True, upload_to='pharmacies/documents/autorisation/'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='document_cin',
            field=models.FileField(blank=True, null=True, upload_to='pharmacies/documents/cin/'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='document_patente',
            field=models.FileField(blank=True, null=True, upload_to='pharmacies/documents/patente/'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='gouvernorat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='matricule_fiscal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='numero_autorisation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
