# Generated by Django 4.2.9 on 2026-03-28 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pharmacistprofile_cin_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CGU', "Conditions Générales d'Utilisation"), ('CONTRAT', 'Contrat de Partenariat'), ('CONFIDENTIALITE', 'Politique de Confidentialité')], max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceptation Légale',
                'verbose_name_plural': 'Acceptations Légales',
            },
        ),
    ]
